export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/TrigentSoftwareInc/Roo-Code",
	GITHUB_DISCUSSIONS: "https://github.com/TrigentSoftwareInc/Roo-Code/discussions",
	DISCORD: "https://discord.gg/Galaxia",
	REDDIT: "https://reddit.com/r/Galaxia",
	X: "https://x.com/Galaxia",
	LINKEDIN: "https://www.linkedin.com/company/roo-code",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/Galaxia.bsky.social",
	YOUTUBE: "https://www.youtube.com/@GalaxiaYT",
	DOCUMENTATION: "",
	CAREERS: "",
	ISSUES: "https://github.com/TrigentSoftwareInc/Roo-Code/issues",
	FEATURE_REQUESTS: "https://github.com/TrigentSoftwareInc/Roo-Code/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/TrigentSoftwareInc/Roo-Code/discussions",
	CHANGELOG: "https://github.com/TrigentSoftwareInc/Roo-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/TrigentSoftwareInc/Roo-Code/blob/main/PRIVACY.md",
	INTEGRATIONS: "/community",
	TUTORIALS: "/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=TrigentSoftwareInc.galaxia",
	SECURITY: "https://trust.Galaxia.com",
	EVALS: "https://trigent.com//evals",
	BLOG: "https://blog.Galaxia.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@GalaxiaYT/podcasts",
	FAQ: "https://trigent.com//#faq",
	TESTIMONIALS: "https://trigent.com//#testimonials",
	CLOUD_APP_LOGIN: "/sign-in",
	CLOUD_APP_SIGNUP: "/sign-up",
	CLOUD_APP_SIGNUP_PRO: "/sign-up?redirect_url=/cloud-agents/setup",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
